# Generated by Django 2.1.7 on 2019-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='main_image',
            field=models.ImageField(upload_to='static/img/'),
        ),
    ]
