# Generated by Django 2.1.7 on 2019-05-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0002_auto_20190526_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Fact_Name', max_length=100)),
                ('description', models.TextField()),
                ('main_image', models.ImageField(upload_to='static/img/')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('change_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(default='Station_Name', max_length=100),
        ),
    ]
