# Generated by Django 2.1.7 on 2019-05-26 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0004_auto_20190526_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='fact',
            name='alt_image',
            field=models.CharField(default='Alt_text', max_length=200),
        ),
    ]
