# Generated by Django 2.1.7 on 2019-05-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0005_fact_alt_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img/')),
                ('alt_image', models.CharField(default='Alt_text', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='fact',
            name='alt_image',
        ),
        migrations.AlterField(
            model_name='fact',
            name='main_image',
            field=models.ForeignKey(on_delete='Cascade', to='U_stations.image'),
        ),
        migrations.AlterField(
            model_name='station',
            name='name',
            field=models.CharField(default='Station_Name', max_length=100, verbose_name='Station name'),
        ),
    ]
