# Generated by Django 2.1.7 on 2019-05-26 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0006_auto_20190526_1851'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img',
            new_name='path',
        ),
    ]
