# Generated by Django 2.1.7 on 2019-05-26 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0009_auto_20190526_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='path',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(null=True, upload_to='media/images/%Y/%m/%d'),
        ),
    ]
