# Generated by Django 2.1.7 on 2019-05-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('U_stations', '0010_auto_20190526_2131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='alt_image',
            new_name='alt_text',
        ),
        migrations.AlterField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y_%m_%d'),
        ),
    ]
